#!/bin/bash
echo $$ > task6_pid
a=1
mode="work"
term()
{
	mode="cancel"
}
trap 'term' SIGTERM
while true
do
	case $mode in
		"work")
			let a=$a+1
			echo $a
			;;
		"cancel")
			echo "Stopped by SIGTERM"
			exit
			;;
	esac
	sleep 2
done
