#!/bin/bash
echo $$ > task7_pid
a=1
mode="+"
usr1()
{
mode="+"
}
usr2()
{
mode="*"
}
term()
{
mode="cancel"
}
trap 'usr1' USR1
trap 'usr2' USR2
trap 'term' SIGTERM
while true
do
	case $mode in
		"+") 
			let a=$a+2
			echo $a
			;;
		"*")
			let a=$a*2
			echo $a
			;;
		"cancel")
			echo "Cancel"
			exit
	esac
	sleep 2
done
